/*
 * File:  DemographicInfo.java
 * @author David Olenjack
 * Date:  01-27-2016
 * Purpose:  Create a program in Java to obtain and display certain information from an end user
 * Instructor: D. Didulo
 * 
 * @version 1.0
 * 
 * Author Note:  
 * 
 * One of my favorite parts about programming is making my code "squeaky clean" and well organized. I am using the Eclipse IDE 
 * in lieu of a generic text editor due to the ability to vary the colors of the text to keep things organized and pleasing to the eyes
 * while I write the code for this project.
 * 
 * All code below has been entered by my hand unless otherwise specified.  I will use two different annotations for code that I did not
 * type out.  The first will be "//AG" for code that has been automatically generated by the IDE.  The second will be "//CP" for code
 * that I have Copied and Pasted.  I don't anticipate a great deal of either of these two annotations, and will provide justification 
 * for the latter of the two.
 */



// Class Import
import java.util.Scanner;

public class DemographicInfo { // AG

	// Begin main method

	public static void main(String[] args) { // AG

		// Class Constructors
		Scanner scIn = new Scanner(System.in);

		// Declare variables
		int birthMonth = 0;
		int birthDay = 0;
		int birthYear = 0;
		double latitude = 0.0;
		double longitude = 0.0;
		double gpa = 0.0;
		
		// Give program description to End User
		
		System.out.println("This program will gather information about you and present it back to you in a pleasant and tidy format!");
		System.out.println(""); // line spacing for a cleaner look
				
		//  Gather info from End User and validate that info
				
		//  birthMonth
		do{
			System.out.println("");
			System.out.println("Please enter the month you were born (1-12):");
			while (!scIn.hasNextInt()){
				System.out.println("");
				System.out.println("That is not a valid entry. Your entry must be a number between 1 and 12.");
				scIn.next(); // advance the scanner past the input
		    }
			birthMonth = scIn.nextInt();
			
			if (birthMonth < 1 || birthMonth > 12){  // if birthMonth isn't within allowed range give error message
				System.out.println("");
				System.out.println(birthMonth+ " is not a valid month. Please try again.");
			}
		} while (birthMonth < 1 || birthMonth > 12);  // if birthMonth isn't within allowed range start the loop over
		
		//  birthDay
		do{
			System.out.println("");
			System.out.println("Please enter the day you were born (1-31):");
			while (!scIn.hasNextInt()){
				System.out.println("");
				System.out.println("That is not a valid entry. Your entry must be a number between 1 and 31.");
				scIn.next(); 
			}
			birthDay = scIn.nextInt();
			
			if (birthDay < 1 || birthDay > 31){
				System.out.println("");
				System.out.println(birthDay+" is not a valid day.  Please try again.");
			}
		} while (birthDay < 1 || birthDay > 31);
		
		//  birthYear
		do{
			System.out.println("");
			System.out.println("Please enter the year you were born (1900-2016):");
			while (!scIn.hasNextInt()){
				System.out.println("");
				System.out.println("That is not a valid entry. Your entry bust be a number between 1900 and 2016.");
				scIn.next();
			}
			birthYear = scIn.nextInt();
			
			if (birthYear < 1900 || birthYear > 2016){
				System.out.println("");
				System.out.println(birthYear+ " is not a valid year for this survey. Please try again.");
			}
		} while (birthYear < 1900 || birthYear > 2016);
		
		//  latitude
		do{
			System.out.println("");
			System.out.println("Please enter the latitude of your home address:");
			while (!scIn.hasNextDouble()){
				System.out.println("");
				System.out.println("That is not a valid entry. Your entry must be in a decimal format. e.g. 23.55234.");
				scIn.next();
			}
			latitude = scIn.nextDouble();
		} while (latitude <= 0);
		
		//  longitude
		do{
			System.out.println("");
			System.out.println("Please enter the longitude of your home address:");
			while (!scIn.hasNextDouble()){
				System.out.println("");
				System.out.println("That is not a valid entry. Your entry must be in a decimal format. e.g. 23.55234.");
				scIn.next();
			}
			longitude = scIn.nextDouble();
		} while (longitude <= 0);
		
		//  gpa
		do{
			System.out.println("");
			System.out.println("Please enter your GPA(0.0-4.0):");
			while (!scIn.hasNextDouble()){
				System.out.println("");
				System.out.println("That is not a valid entry. Your entry must be in a decimal format between 0.0 and 4.0.");
				scIn.next();
			}
			gpa = scIn.nextDouble();
			
			if (gpa < 0.0 || gpa > 4.0){
				System.out.println("");
				System.out.println(gpa+ " is not a valid GPA for this survey. Please try again.");
			}
		} while (gpa < 0.0 || gpa > 4.0);
		
		
		//  Declare monthString and complete Switch for converting birthMonth to monthString
		
		String monthString;
		
		switch (birthMonth) {
		case 1:  monthString = "January";
		break;
		case 2:  monthString = "February";
		break;
		case 3:  monthString = "March";
		break;
		case 4:  monthString = "April";
		break;
		case 5:  monthString = "May";
		break;
		case 6:  monthString = "June";
		break;
		case 7:  monthString = "July";
		break;
		case 8:  monthString = "August";
		break;
		case 9:  monthString = "September";
		break;
		case 10:  monthString = "October";
		break;
		case 11:  monthString = "November";
		break;
		case 12:  monthString = "December";
		break;
		default :  monthString = "Invalid Month";
		break;
				
		}
			
		// begin output
		System.out.println("");
		System.out.println("");
		System.out.println("**************************************************************************************");
		System.out.println("* Thank you for participating in this survey!  Here is the information you provided! *");
		System.out.println("**************************************************************************************");
				
		System.out.println("");
		System.out.println("");
		System.out.println("Birthday: " +monthString +" " +birthDay +", " +birthYear);
		System.out.println("Address: Latitude " +latitude +"\u00B0, Longitude " +longitude +"\u00B0");
		System.out.println("Current GPA: " +gpa);
		
		System.out.println("");
		System.out.println("");
		System.out.println("The program is now complete and will exit.  Thank you for your time.");
		
		
	} // AG

} // AG
